# Generated by Django 3.2 on 2021-05-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YoE', models.IntegerField()),
                ('industry', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dateadded', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('isAgeViewable', models.IntegerField()),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
    ]
