# Generated by Django 3.1.7 on 2021-03-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='aqe',
            new_name='age',
        ),
    ]
